import {
  HeaderParams,
  Master,
  TestUser,
  User,
  KeyValueString,
  TableConfig,
  Lov,
} from "./AppTypes";
import {
  CityMasterColumns,
  LovReferenceKey,
  OrganizationMasterColumns,
  ProductMasterColumns,
  LoanProductColumns,
  LoanPurposeColumns,
  SourcingFormInitialData,
  PetsonalFormInitialData,
  KYCFormInitialData,
  IncomeFormInitialData,
  LoanFormInitialData,
  StateMasterColumns,
  StaticDataColumns,
  StaticMasterData,
  SubProductColumns,
} from "./AppStaticData";

export {
  Master,
  User,
  StaticMasterData,
  SourcingFormInitialData,
  PetsonalFormInitialData,
  KYCFormInitialData,
  IncomeFormInitialData,
  LoanFormInitialData,
  HeaderParams,
  TestUser,
  KeyValueString,
  OrganizationMasterColumns,
  ProductMasterColumns,
  SubProductColumns,
  LoanProductColumns,
  LoanPurposeColumns,
  TableConfig,
  StaticDataColumns,
  LovReferenceKey,
  Lov,
  StateMasterColumns,
  CityMasterColumns,
};
